sortStrings
js-tasks-ru/js-20230407_aleksandr992 pull request #2
Opened 2023-04-13 12:58 UTC by AlexanderFuse

2023-04-13 12:59 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2023-04-13 13:55 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-04-13 14:59 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2023-04-13 15:45 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2023-04-17 21:58 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    return sortedArray.reverse();
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2023-04-17 21:59 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +export const pick = (obj, ...fields) => Object.fromEntries(
good 👍

2023-04-17 21:59 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
>   */
good 👍

2023-04-17 21:59 UTC, dosandk requested changes
решение sortStrings следует поправить

2023-04-21 11:10 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-04-21 11:20 UTC, AlexanderFuse commented on 02-javascript-data-types/1-sort-strings/index.js
> +    return sortedArray.reverse();
done

2023-04-21 16:37 UTC, dosandk approved these changes
👍 good

2023-04-21 16:37 UTC, merged